# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'surgo-ios-1635' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for surgo-ios-1635
  pod 'IQKeyboardManager'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'PTCardTabBar'
  pod 'FSCalendar'
  pod 'JTAppleCalendar'
  pod 'CropViewController'
  pod 'OpalImagePicker'
  pod 'YPImagePicker'
  pod 'NVActivityIndicatorView', '~> 4.8.0'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseAuth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'PieCharts'

  target 'surgo-ios-1635Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'surgo-ios-1635UITests' do
    # Pods for testing
  end

end
